import re
from datetime import datetime


def _clean_markdown(text: str) -> str:
    """Strip markdown syntax for plain text export."""
    text = re.sub(r"#{1,6}\s*", "", text)        # Remove headings
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text) # Bold
    text = re.sub(r"\*(.*?)\*",   r"\1", text)   # Italic
    text = re.sub(r"`(.*?)`",     r"\1", text)   # Inline code
    return text.strip()


def export_txt(summary_text: str, summary_type: str, video_title: str) -> str:
    """Export summary as plain text."""
    header = (
        f"YouTube AI Summarizer — {summary_type} Summary\n"
        f"Video: {video_title}\n"
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
        f"{'=' * 60}\n\n"
    )
    return header + _clean_markdown(summary_text)


def export_markdown(summary_text: str, summary_type: str, video_title: str, video_url: str = "") -> str:
    """Export summary as Markdown file."""
    lines = [
        f"# {summary_type} Summary",
        f"",
        f"**Video:** [{video_title}]({video_url})" if video_url else f"**Video:** {video_title}",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"",
        f"---",
        f"",
        summary_text.strip(),
        f"",
        f"---",
        f"*Generated by YouTube AI Summarizer*",
    ]
    return "\n".join(lines)


def get_export_filename(summary_type: str, extension: str) -> str:
    """Generate a timestamped filename for export."""
    ts = datetime.now().strftime("%Y%m%d_%H%M")
    safe_type = summary_type.lower().replace(" ", "_")
    return f"summary_{safe_type}_{ts}.{extension}"